language: scala
scala:
   - 2.12.4
jdk:
   - oraclejdk8
sudo: required
services:
  - docker
script:
   - sbt ++$TRAVIS_SCALA_VERSION dockerComposeUp
   - ES_BIN_PORT=9300 ; nc -z 0.0.0.0 ${ES_BIN_PORT} && echo "OK PORT(${ES_BIN_PORT}): $?" || echo "FAILED PORT(${ES_BIN_PORT}): $?"
   - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport codacyCoverage
   - sbt ++$TRAVIS_SCALA_VERSION dockerComposeStop
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/15b5367e5ba965a65a9a
    on_success: change
    on_failure: always
    on_start: never
