language: scala
scala:
   - 2.12.4
jdk:
   - oraclejdk8
sudo: required
services:
  - docker
script:
   - sbt ++$TRAVIS_SCALA_VERSION dockerComposeUp
   - nc -z 0.0.0.0 9300 && echo "OK" || echo "FAILED"
   - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport codacyCoverage
   - sbt ++$TRAVIS_SCALA_VERSION dockerComposeStop
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/15b5367e5ba965a65a9a
    on_success: change
    on_failure: always
    on_start: never
