version: "3.2"
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    network_mode: "host"
    restart: unless-stopped
    command: elasticsearch
    volumes:
      - ./elasticsearch/config:/usr/share/elasticsearch/config
      - ./elasticsearch_test/logs:/usr/share/elasticsearch/logs
    environment:
      - MAX_LOCKED_MEMORY=unlimited

